"""
Security Header Scanner — Generated by security_company plugin

Scans a web target for missing security headers and grades the result (A+ to F).

Usage: python scanners/header_scanner.py --target https://example.com
       python scanners/header_scanner.py --target https://example.com --json
"""
import argparse
import json
import sys
from urllib.request import Request, urlopen
from urllib.error import URLError, HTTPError

HEADERS_TO_CHECK = {
    "Content-Security-Policy": {
        "severity": "critical",
        "score": 20,
        "description": "Controls which resources the browser can load for the page."
    },
    "X-Frame-Options": {
        "severity": "high",
        "score": 15,
        "description": "Prevents clickjacking by controlling iframe embedding."
    },
    "X-Content-Type-Options": {
        "severity": "high",
        "score": 10,
        "description": "Prevents MIME-type sniffing (nosniff)."
    },
    "Strict-Transport-Security": {
        "severity": "high",
        "score": 15,
        "description": "Enforces HTTPS connections (HSTS)."
    },
    "Referrer-Policy": {
        "severity": "medium",
        "score": 10,
        "description": "Controls how much referrer information is sent."
    },
    "Permissions-Policy": {
        "severity": "medium",
        "score": 10,
        "description": "Restricts browser features (camera, microphone, geolocation, etc)."
    },
    "Cache-Control": {
        "severity": "low",
        "score": 5,
        "description": "Controls caching behavior of the response."
    },
    "X-XSS-Protection": {
        "severity": "low",
        "score": 5,
        "description": "Legacy XSS filter (deprecated in modern browsers)."
    },
    "Cross-Origin-Opener-Policy": {
        "severity": "medium",
        "score": 5,
        "description": "Isolates browsing context (prevents Spectre attacks)."
    },
    "Cross-Origin-Resource-Policy": {
        "severity": "medium",
        "score": 5,
        "description": "Controls cross-origin resource fetches."
    },
    "Cross-Origin-Embedder-Policy": {
        "severity": "medium",
        "score": 5,
        "description": "Prevents loading cross-origin resources without explicit permission."
    },
}

SEVERITY_COLORS = {"critical": "31", "high": "33", "medium": "35", "low": "36"}
RESET = "\033[0m"


def grade(score):
    if score >= 95: return "A+"
    if score >= 90: return "A"
    if score >= 80: return "B"
    if score >= 70: return "C"
    if score >= 50: return "D"
    return "F"


def scan(target):
    if not target.startswith("http"):
        target = "https://" + target

    req = Request(target, headers={"User-Agent": "MYC-Security-Scanner/1.0"})
    results = {"target": target, "headers": {}, "score": 100, "grade": ""}

    try:
        resp = urlopen(req, timeout=10)
        resp_headers = {k.lower(): v for k, v in resp.getheaders()}
    except (URLError, HTTPError) as e:
        print(f"ERRO ao conectar a {target}: {e}", file=sys.stderr)
        sys.exit(1)

    for header, info in HEADERS_TO_CHECK.items():
        key = header.lower()
        present = key in resp_headers
        value = resp_headers.get(key, None)

        results["headers"][header] = {
            "present": present,
            "value": value,
            "severity": info["severity"],
            "score_penalty": info["score"] if not present else 0,
            "description": info["description"],
        }

        if not present:
            results["score"] -= info["score"]

    results["grade"] = grade(results["score"])
    return results


def print_report(results, as_json=False):
    grade_colors = {"A+": "32", "A": "32", "B": "33", "C": "33", "D": "31", "F": "31"}

    if as_json:
        print(json.dumps(results, indent=2))
        return

    print(f"\n{'='*60}")
    print(f"  MYC Security Header Scanner")
    print(f"{'='*60}")
    print(f"  Alvo:  {results['target']}")
    gc = grade_colors.get(results['grade'], '37')
    print(f"  Nota:  \033[{gc}m{results['grade']}\033[0m ({results['score']}/100)")
    print(f"{'='*60}\n")

    missing, found = [], []
    for h, info in results["headers"].items():
        sev = info["severity"]
        c = SEVERITY_COLORS.get(sev, "37")
        if info["present"]:
            found.append((h, info))
        else:
            missing.append((h, info))

    print(f"  \033[32m[{len(found)} encontrados]\033[0m")
    for h, info in found:
        print(f"    \033[32mOK\033[0m  {h}: \033[36m{info['value']}\033[0m")

    if missing:
        print(f"\n  \033[31m[{len(missing)} ausentes]\033[0m")
        for h, info in missing:
            print(f"    \033[{c}m[{info['severity'].upper()}]\033[0m  {h}")
            print(f"           {info['description']}")

    # Quick recommendations
    print(f"\n{'='*60}")
    print("  Recomendacoes rapidas:")
    print(f"{'='*60}")
    for h, info in missing:
        if h == "Content-Security-Policy":
            print(f"  -> Defina CSP: default-src 'self'; script-src 'self' 'unsafe-inline'")
        elif h == "Strict-Transport-Security":
            print(f"  -> Defina HSTS: max-age=31536000; includeSubDomains")
        elif h == "X-Frame-Options":
            print(f"  -> Defina X-Frame-Options: DENY ou SAMEORIGIN")
        elif h == "X-Content-Type-Options":
            print(f"  -> Defina X-Content-Type-Options: nosniff")
        elif h == "Referrer-Policy":
            print(f"  -> Defina Referrer-Policy: strict-origin-when-cross-origin")

    print(f"\n{'='*60}\n")


def main():
    parser = argparse.ArgumentParser(description="Security Header Scanner")
    parser.add_argument("--target", "-t", required=True, help="URL para escanear")
    parser.add_argument("--json", action="store_true", help="Saida em JSON")
    args = parser.parse_args()
    results = scan(args.target)
    print_report(results, as_json=args.json)


if __name__ == "__main__":
    main()
