"""
Non-destructive Port Scanner — Generated by security_company plugin

Scans a target host for open ports (1-1024 + common high ports).
Uses threading for speed.

Usage: python scanners/port_scanner.py --target example.com
"""
import argparse
import socket
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed

COMMON_PORTS = {
    21: "FTP", 22: "SSH", 23: "Telnet", 25: "SMTP", 53: "DNS",
    80: "HTTP", 110: "POP3", 143: "IMAP", 443: "HTTPS", 993: "IMAPS",
    995: "POP3S", 3306: "MySQL", 5432: "PostgreSQL", 6379: "Redis",
    8080: "HTTP-Proxy", 8443: "HTTPS-Alt", 27017: "MongoDB",
}

def scan_port(host, port, timeout=1):
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.settimeout(timeout)
        result = s.connect_ex((host, port))
        s.close()
        return port if result == 0 else None
    except (socket.error, socket.timeout):
        return None

def scan(host, port_range_start=1, port_range_end=1024, common_high=False, max_workers=100):
    ports_to_scan = list(range(port_range_start, port_range_end+1))
    if common_high:
        ports_to_scan.extend(COMMON_PORTS.keys())
    ports_to_scan = sorted(set(ports_to_scan))

    open_ports = []
    total = len(ports_to_scan)
    scanned = [0]

    print(f"Escaneando {host}: {total} portas...")
    start = time.time()

    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        future_to_port = {
            executor.submit(scan_port, host, port): port
            for port in ports_to_scan
        }
        for future in as_completed(future_to_port):
            port = future.result()
            if port:
                service = COMMON_PORTS.get(port, "Unknown")
                open_ports.append((port, service))
                print(f"  [ABERTA] {port}/tcp ({service})")
            scanned[0] += 1
            if scanned[0] % 200 == 0:
                pct = scanned[0]/total*100
                print(f"  Progresso: {pct:.0f}%")

    elapsed = time.time() - start
    open_ports.sort()
    return open_ports, elapsed

def main():
    parser = argparse.ArgumentParser(description="Port Scanner")
    parser.add_argument("--target", "-t", required=True, help="Host para escanear")
    parser.add_argument("--start", default=1, type=int, help="Primeira porta")
    parser.add_argument("--end", default=1024, type=int, help="Ultima porta")
    parser.add_argument("--common-high", action="store_true", help="Inclui portas altas comuns")
    args = parser.parse_args()

    target = args.target
    try:
        ip = socket.gethostbyname(target)
    except socket.gaierror:
        print(f"Nao foi possivel resolver: {target}")
        sys.exit(1)

    print(f"Alvo: {target} ({ip})")
    print(f"Portas: {args.start}-{args.end}")
    open_ports, elapsed = scan(ip, args.start, args.end, args.common_high)

    print(f"\n{'='*50}")
    print(f"Resultado: {len(open_ports)} portas abertas em {elapsed:.1f}s")
    if not open_ports:
        print("Nenhuma porta aberta encontrada.")
    else:
        print(f"{'Porta':<10} {'Servico':<15}")
        print(f"{'-'*25}")
        for port, svc in open_ports:
            print(f"{port:<10} {svc:<15}")
    print(f"{'='*50}\n")

if __name__ == "__main__":
    main()
