"""
Space Shooter — Pygame

Generated by the game_studio_company plugin workflow from MYC.

Controls: Arrow keys/WASD = Move | Space = Shoot | P = Pause | ESC = Quit
Run: pip install pygame && python game.py
"""
import math
import random
import sys
import pygame

pygame.init()
SCREEN_W, SCREEN_H = 640, 800
FPS = 60
DARK_BLUE = (10, 10, 40)

FONT_L = pygame.font.SysFont("consolas", 48)
FONT_M = pygame.font.SysFont("consolas", 24)
FONT_S = pygame.font.SysFont("consolas", 18)

def draw_text(surf, text, size, x, y, color=(255,255,255), font=None):
    f = font or pygame.font.SysFont("consolas", size)
    img = f.render(text, True, color)
    r = img.get_rect(center=(x, y))
    surf.blit(img, r)

def make_sound(freq, ms):
    sr = 22050
    n = int(sr * ms / 1000)
    buf = bytearray(n * 2)
    for i in range(n):
        t = i / sr
        v = 12000 if math.sin(2 * math.pi * freq * t) > 0 else -12000
        e = max(0, 1 - i/n)**2
        v = int(v * e)
        buf[i*2] = v & 0xFF
        buf[i*2+1] = (v >> 8) & 0xFF
    return pygame.mixer.Sound(buffer=buf)

snd_shoot = make_sound(880, 80)
snd_hit = make_sound(200, 120)
snd_boom = make_sound(80, 300)
snd_powerup = make_sound(660, 200)
snd_levelup = make_sound(440, 400)

class Player(pygame.sprite.Sprite):
    def __init__(self):
        super().__init__()
        self.image = pygame.Surface((50,40), pygame.SRCALPHA)
        pygame.draw.polygon(self.image, (80,220,255), [(25,0),(0,40),(12,30),(25,35),(38,30),(50,40)])
        self.rect = self.image.get_rect(centerx=SCREEN_W//2, bottom=SCREEN_H-30)
        self.speed = 6
        self.lives = 3
        self.wpn = 1
        self.shield = False
        self.shield_t = 0
        self.invinc = False
        self.invinc_t = 0
        self.cooldown = 0
        self.flash = 0

    def update(self):
        keys = pygame.key.get_pressed()
        if keys[pygame.K_LEFT] or keys[pygame.K_a]: self.rect.x -= self.speed
        if keys[pygame.K_RIGHT] or keys[pygame.K_d]: self.rect.x += self.speed
        if keys[pygame.K_UP] or keys[pygame.K_w]: self.rect.y -= self.speed
        if keys[pygame.K_DOWN] or keys[pygame.K_s]: self.rect.y += self.speed
        self.rect.clamp_ip(pygame.Rect(0,0,SCREEN_W,SCREEN_H))
        if self.cooldown > 0: self.cooldown -= 1
        if keys[pygame.K_SPACE] and self.cooldown <= 0: self.shoot()
        if self.invinc:
            self.invinc_t -= 1
            self.flash ^= 1
            if self.invinc_t <= 0: self.invinc = False; self.flash = 0
        if self.shield:
            self.shield_t -= 1
            if self.shield_t <= 0: self.shield = False

    def shoot(self):
        rate = max(5, 15 - self.wpn*2)
        self.cooldown = rate
        snd_shoot.play()
        b = Bullet(self.rect.centerx, self.rect.top)
        all_s.add(b); bullets.add(b)
        if self.wpn >= 2:
            for dx in (-8,8):
                b = Bullet(self.rect.centerx+dx, self.rect.top)
                all_s.add(b); bullets.add(b)
        if self.wpn >= 3:
            for dx in (-16,16):
                b = Bullet(self.rect.centerx+dx, self.rect.top+5, -1.5 if dx<0 else 1.5, -9)
                all_s.add(b); bullets.add(b)

    def hit(self):
        if self.invinc: return
        if self.shield: self.shield = False; snd_hit.play(); return
        self.lives -= 1
        self.invinc = True; self.invinc_t = 90
        self.wpn = max(1, self.wpn-1)
        snd_boom.play()

class Bullet(pygame.sprite.Sprite):
    def __init__(self, x, y, vx=0, vy=-10):
        super().__init__()
        self.image = pygame.Surface((4,12), pygame.SRCALPHA)
        pygame.draw.rect(self.image, (255,255,80), (0,0,4,12), border_radius=2)
        self.rect = self.image.get_rect(center=(x,y))
        self.vx = vx; self.vy = vy
    def update(self):
        self.rect.x += self.vx; self.rect.y += self.vy
        if self.rect.bottom < 0 or self.rect.top > SCREEN_H: self.kill()

class Enemy(pygame.sprite.Sprite):
    TYPES = {"scout":1,"drone":2,"cruiser":5,"boss":50}
    def __init__(self, t, lvl=1):
        super().__init__()
        self.t = t; self.hp = self.TYPES[t] + lvl*2
        self.max_hp = self.hp
        self.tmr = random.randint(30,120)
        self.tt = random.uniform(0,100)
        self.phase = random.uniform(0, 2*math.pi)
        if   t=="scout":
            self.image = pygame.Surface((30,20), pygame.SRCALPHA)
            pygame.draw.polygon(self.image,(255,50,50),[(15,0),(0,20),(30,20)])
            self.spd = 2+lvl*0.2; self.pts = 100
        elif t=="drone":
            self.image = pygame.Surface((28,28), pygame.SRCALPHA)
            pygame.draw.rect(self.image,(255,160,30),(4,4,20,20),border_radius=4)
            self.spd = 1.5+lvl*0.2; self.pts = 200
        elif t=="cruiser":
            self.image = pygame.Surface((36,30), pygame.SRCALPHA)
            pygame.draw.polygon(self.image,(180,80,255),[(18,0),(0,15),(6,30),(30,30),(36,15)])
            self.spd = 1+lvl*0.1; self.pts = 400
        elif t=="boss":
            self.image = pygame.Surface((100,60), pygame.SRCALPHA)
            pygame.draw.polygon(self.image,(255,50,50),[(50,0),(0,30),(20,60),(80,60),(100,30)])
            pygame.draw.polygon(self.image,(255,160,30),[(50,10),(15,30),(25,55),(75,55),(85,30)])
            self.rect = self.image.get_rect(centerx=SCREEN_W//2, top=50)
            self.spd = 1; self.pts = 5000; self.mt = 0; self.tmr = 20

    def update(self):
        self.tt += 0.02
        if self.t == "scout":
            self.rect.y += self.spd
            self.rect.x += math.sin(self.phase+self.tt*3)*3
        elif self.t in ("drone","cruiser"):
            self.rect.y += self.spd
            self.tmr -= 1
            if self.tmr <= 0:
                b = Bullet(self.rect.centerx, self.rect.bottom, 0, 5)
                all_s.add(b); ebullets.add(b)
                self.tmr = random.randint(60,120)
        elif self.t == "boss":
            self.mt += 0.02
            self.rect.y += self.spd*0.5
            if self.rect.top > 80: self.rect.y -= self.spd*0.5
            self.rect.x += math.sin(self.mt)*3
            self.tmr -= 1
            if self.tmr <= 0:
                # Spread + targeted shots
                for a in range(-3,4):
                    b = Bullet(self.rect.centerx, self.rect.bottom, a*1.2, 4)
                    all_s.add(b); ebullets.add(b)
                if player.alive():
                    dx=player.rect.centerx-self.rect.centerx
                    dy=player.rect.centery-self.rect.centery
                    d=max(1,math.hypot(dx,dy))
                    b = Bullet(self.rect.centerx, self.rect.bottom, dx/d*5, dy/d*5)
                    all_s.add(b); ebullets.add(b)
                self.tmr = max(10, 30-self.hp//5)
        if self.rect.top > SCREEN_H+50: self.kill()

class PowerUp(pygame.sprite.Sprite):
    def __init__(self, x, y):
        super().__init__()
        r = random.random()
        if r < 0.5: self.pt="w"; self.c=(50,255,100)
        elif r < 0.8: self.pt="s"; self.c=(80,220,255)
        else: self.pt="l"; self.c=(255,50,50)
        self.image = pygame.Surface((20,20), pygame.SRCALPHA)
        pygame.draw.circle(self.image, self.c, (10,10), 10)
        pygame.draw.circle(self.image, (255,255,255), (10,10), 6, 2)
        self.rect = self.image.get_rect(center=(x,y))
    def update(self):
        self.rect.y += 2
        if self.rect.top > SCREEN_H: self.kill()

class Particle(pygame.sprite.Sprite):
    def __init__(self, x, y, c, life=30):
        super().__init__()
        sz = random.randint(2,5)
        self.image = pygame.Surface((sz,sz), pygame.SRCALPHA)
        pygame.draw.rect(self.image, c, (0,0,sz,sz))
        self.rect = self.image.get_rect(center=(x,y))
        a = random.uniform(0,2*math.pi); spd = random.uniform(1,6)
        self.vx = math.cos(a)*spd; self.vy = math.sin(a)*spd
        self.life = life; self.ml = life
    def update(self):
        self.rect.x += self.vx; self.rect.y += self.vy
        self.vx *= 0.96; self.vy *= 0.96
        self.life -= 1
        self.image.set_alpha(max(0,int(255*self.life/self.ml)))
        if self.life <= 0: self.kill()

class Star(pygame.sprite.Sprite):
    def __init__(self):
        super().__init__()
        sz = random.choice([1,1,1,2,3]); br = random.randint(80,255)
        self.image = pygame.Surface((sz,sz), pygame.SRCALPHA)
        self.image.fill((br,br,br,255))
        self.rect = self.image.get_rect(x=random.randint(0,SCREEN_W), y=random.randint(0,SCREEN_H))
        self.spd = 0.5+sz*0.5
    def update(self):
        self.rect.y += self.spd
        if self.rect.top > SCREEN_H:
            self.rect.y = -self.rect.height; self.rect.x = random.randint(0,SCREEN_W)

# Globals
all_s = pygame.sprite.Group(); bullets = pygame.sprite.Group()
ebullets = pygame.sprite.Group(); enemies = pygame.sprite.Group()
powerups = pygame.sprite.Group(); particles = pygame.sprite.Group()
stars = pygame.sprite.Group()

score = 0; hi_score = 0; level = 1; lives = 3
wpn_level = 1; shield = False; shield_t = 0
kills = 0; spawned = 0; to_spawn = 10
trans_t = 0; game_over = False; started = False

screen = pygame.display.set_mode((SCREEN_W, SCREEN_H))
pygame.display.set_caption("Space Shooter — MYC game_studio_company")
clock = pygame.time.Clock()

def spawn_explode(x,y,n=15,c=(255,160,30)):
    for _ in range(n):
        p = Particle(x,y,c); all_s.add(p); particles.add(p)

screen_obj = pygame.sprite.Group()
player = None

def init_game():
    global player, score, level, lives, wpn_level, kills, spawned, to_spawn, trans_t, shield, shield_t
    score = 0; level = 1; lives = 3; wpn_level = 1; kills = 0; spawned = 0; to_spawn = 10; trans_t = 0; shield = False; shield_t = 0
    all_s.empty(); bullets.empty(); ebullets.empty(); enemies.empty(); powerups.empty(); particles.empty(); stars.empty()
    player = Player(); all_s.add(player); screen_obj.add(player)
    for _ in range(80):
        s = Star(); all_s.add(s); stars.add(s)

running = True
init_game()

while running:
    clock.tick(FPS)
    for e in pygame.event.get():
        if e.type == pygame.QUIT: running = False
        if e.type == pygame.KEYDOWN:
            if e.key == pygame.K_ESCAPE: running = False
            if e.key == pygame.K_RETURN and not started: started = True; init_game()
            if e.key == pygame.K_RETURN and game_over: init_game(); game_over = False; started = True

    stars.update()

    if not started:
        screen.fill(DARK_BLUE); stars.draw(screen)
        draw_text(screen,"SPACE SHOOTER",60,SCREEN_W//2,SCREEN_H//3,(80,220,255),FONT_L)
        draw_text(screen,"MYC game_studio_company plugin project",16,SCREEN_W//2,SCREEN_H//3+45,(150,150,170),FONT_S)
        draw_text(screen,"Press ENTER to start",28,SCREEN_W//2,SCREEN_H//2+50,(255,255,255),FONT_M)
        pygame.display.flip(); continue

    if game_over:
        screen.fill(DARK_BLUE); stars.draw(screen)
        draw_text(screen,"GAME OVER",60,SCREEN_W//2,SCREEN_H//3,(255,50,50),FONT_L)
        draw_text(screen,f"Score: {score}",30,SCREEN_W//2,SCREEN_H//2+20,(80,220,255),FONT_M)
        draw_text(screen,f"High Score: {hi_score}",24,SCREEN_W//2,SCREEN_H//2+65,(255,255,80),FONT_M)
        draw_text(screen,f"Reached Level {level} | {kills} kills",20,SCREEN_W//2,SCREEN_H//2+100,(150,150,170),FONT_M)
        draw_text(screen,"Press ENTER to retry",24,SCREEN_W//2,SCREEN_H-80,(255,255,255),FONT_M)
        pygame.display.flip(); continue

    if not all_s.empty():
        all_s.update()

    # Spawn enemies
    if spawned < to_spawn and random.random() < 0.02+level*0.005:
        r = random.random()
        if level>=5 and r<0.02 and not any(e.t=="boss" for e in enemies):
            en = Enemy("boss",level)
        elif level>=3 and r<0.12: en = Enemy("cruiser",level)
        elif r<0.35: en = Enemy("drone",level)
        else: en = Enemy("scout",level)
        en.rect.x = random.randint(20,SCREEN_W-20)
        en.rect.y = random.randint(-80,-30)
        all_s.add(en); enemies.add(en)
        spawned += 1

    # Bullet vs enemy
    for en in pygame.sprite.groupcollide(enemies, bullets, False, True):
        en.hp -= 1; snd_hit.play()
        if en.hp <= 0:
            score += en.pts; hi_score = max(hi_score, score); kills += 1
            spawn_explode(en.rect.centerx, en.rect.centery, 20); snd_boom.play()
            if random.random() < 0.15:
                pu = PowerUp(en.rect.centerx, en.rect.centery)
                all_s.add(pu); powerups.add(pu)
            if en.t=="boss":
                for _ in range(50):
                    p = Particle(en.rect.centerx, en.rect.centery, random.choice([(255,50,50),(255,160,30),(255,255,80),(255,255,255)]))
                    all_s.add(p); particles.add(p)
                snd_levelup.play()
                level += 1; spawned = 0; to_spawn = 10+level*3; trans_t = 90
            en.kill()

    # Enemy bullet vs player
    for _ in pygame.sprite.spritecollide(player, ebullets, True) if hasattr(locals().get('player',''), 'alive') and player.alive() else []:
        player.hit()

    # Enemy vs player
    for en in pygame.sprite.spritecollide(player, enemies, False):
        player.hit(); en.hp -= 2
        if en.hp <= 0: score += en.pts; spawn_explode(en.rect.centerx, en.rect.centery, 20); en.kill()

    # Powerup vs player
    for pu in pygame.sprite.spritecollide(player, powerups, True):
        snd_powerup.play()
        if pu.pt=="w": player.wpn = min(3, player.wpn+1)
        elif pu.pt=="s": player.shield = True; player.shield_t = 600
        elif pu.pt=="l": player.lives = min(5, player.lives+1)

    if enemies and all(e.rect.top > SCREEN_H for e in enemies):
        for e in enemies[:]: e.kill()

    if hasattr(locals().get('player',''), 'lives') and hasattr(player,'lives') and player.lives <= 0:
        game_over = True; spawn_explode(player.rect.centerx, player.rect.centery, 40, (80,220,255)); snd_boom.play()

    # Draw
    screen.fill(DARK_BLUE); stars.draw(screen)
    all_s.draw(screen)
    draw_text(screen, f"Score: {score}", 20, 100, 20, (80,220,255), FONT_S)
    draw_text(screen, f"Level: {level}", 20, SCREEN_W-100, 20, (50,255,100), FONT_S)
    if hasattr(player, 'lives'):
        for i in range(player.lives):
            pygame.draw.polygon(screen, (80,220,255), [(20+i*20,SCREEN_H-15),(10+i*20,SCREEN_H-5),(30+i*20,SCREEN_H-5)])
        draw_text(screen, f"WPN Lv.{player.wpn}", 16, SCREEN_W-60, SCREEN_H-10, (255,255,80), FONT_S)
        if player.shield: draw_text(screen, "SHIELD", 16, SCREEN_W//2, SCREEN_H-10, (80,220,255), FONT_S)
    for b in enemies:
        if b.t=="boss":
            bw=120; hr=b.hp/b.max_hp
            pygame.draw.rect(screen,(150,150,170),(SCREEN_W//2-bw//2,8,bw,8))
            pygame.draw.rect(screen,(255,50,50),(SCREEN_W//2-bw//2,8,int(bw*hr),8))

    pygame.display.flip()

pygame.quit(); sys.exit()
